### ISSUE TITLE
Up arrow key does not work in bash.exe

### ISSUE THREAD

**Issue by mqudsi** [zeit/hyper#1127]
Running 1.0.0, starting hyper, then starting bash.exe with no other changes or configurations, the up arrow key does not work out of the box. This is on Windows 10 version 1607.

**Comment by khuongduybui** [comment]
Not only up but all arrow keys.
This issue is very common among console emulators on Windows.
See https://conemu.github.io/en/BashOnWindows.html#some-techinfo

**Comment by stefanivic** [comment]
@mqudsi this is an issue with Bash on Windows https://github.com/Microsoft/BashOnWindows/issues/111.
@CodeTheory

**Comment by nolanlawson** [comment]
For the time being I'm using `history` plus `!-1` (to run the last command) or `!106` (to run e.g. the 106th command), but looking forward to a fix from the BOW team!

**Comment by warpdesign** [comment]
Ctrl+x doesn't work eather (could not exit nano).

**Comment by stefanivic** [comment]
@warpdesign you can use Ctrl+Shift+x to exit.

**Comment by stereokai** [comment]
@stefanivic, @Tyriar from the VSCode team is also watching this issue. Maybe both teams can combine efforts?

@Maximus5 of ConEmu was able to develop a solution by translating "native keypresses into Xterm compatible keypresses" is it something relevant to Hyper and worth looking into?

**Comment by Tyriar** [comment]
@stereokai I'm actually in the process of updating https://github.com/Tyriar/pty.js to use winpty@0.4.0 which appears to have fixed this issue: https://github.com/rprichard/winpty/releases

Stay tuned: https://github.com/Tyriar/pty.js/issues/10

**Comment by stereokai** [comment]
That rocks. I hope it ends up working!

**Comment by jonathandelgado** [comment]
Updating `pty.js` may resolve #1174 and #1180 as well, please keep us informed.

**Comment by Tyriar** [comment]
Yes I'm hoping it will fix some other random Windows issues such as these https://github.com/Microsoft/vscode/issues/14613, it's hard to know until it's done though.

**Comment by jcolesio** [comment]
Just wanted to see if you had any luck resolving the arrow issues?

Would love to start using Hyper for my WSL setup.

**Comment by Tyriar** [comment]
@jcolesio should be fixed when node-pty is upgraded to 0.6.0.

**Comment by schmic** [comment]
Until then you can use [mintty/wsltty](https://github.com/mintty/wsltty/releases)

```
shell: 'C:\\Users\\%USERNAME%\\AppData\\Local\\wsltty\\bin\\wslbridge.exe',
shellArgs: ['-t', '-C~', '/bin/zsh'],
```

Replace %USERNAME% with ours as hyper doesn't resolve env variables (yet). Omit the last argument if you use bash instead of zsh.

**Comment by jcolesio** [comment]
Where do I make the following modification?

Thanks

Sent from my iPhone

On Jan 22, 2017, at 4:31 AM, Michael Scherer <notifications@github.com<mailto:notifications@github.com>> wrote:


Until then you can use mintty/wsltty<https://github.com/mintty/wsltty/releases>

shell: 'C:\\Users\\%USERNAME%\\AppData\\Local\\wsltty\\bin\\wslbridge.exe',
shellArgs: ['-t', '-C~', '/bin/zsh'],


Replace %USERNAME% with ours as hyper doesn't resolve env variables (yet). Omit the last argument if you use bash instead of zsh.

-

**Comment by khuongduybui** [comment]
@jcolesio the ```shell: ..., shellArgs: ...``` arguments are set inside hyper settings file.

**Comment by jcolesio** [comment]
Thanks guys, worked perfectly!

**Comment by jcolesio** [comment]
Do you guys have any issues with WSL in hyper that when deleting things from the command line it retains some old characters depending how much I am deleting from the command line?

**Comment by CheshireSwift** [comment]
Yeah, I also have it echoing back my commands before the output of each.

**Comment by nolanlawson** [comment]
This seems fixed, using Windows Insider 15049 and Hyper 1.2.1. Also reported working on 15042: https://github.com/davatron5000/can-i-subsystem-it/pull/4#issuecomment-283368241

**Comment by matheuss** [comment]
Indeed @nolanlawson, it's fixed – I forgot to close 😅 Thank you 🙌

**Comment by matheuss** [comment]
Btw, huge props to @Tyriar :1st_place_medal:

**Comment by Tyriar** [comment]
:tada:

**Comment by stereokai** [comment]
@nolanlawson @matheuss @Tyriar 

That's weird. I've had it working since version 1,2,0, and I'm on Windows 10 14393.693 - I'm not an insider.

**Comment by Tyriar** [comment]
@stereokai it would have been fixed in a Hyper version, not Windows.

**Comment by stereokai** [comment]
@Tyriar I wrote that because 4 days ago @nolanlawson specified his Windows version (recent build from Windows Insider Program), so I thought he meant there was a fix implemented in the Windows build he's on.

> This seems fixed, using Windows Insider 15049 and Hyper 1.2.1. Also reported working on 15042:
> davatron5000/can-i-subsystem-it#4 (comment)
