### ISSUE TITLE
Right click with trackpad causes paste action

### ISSUE THREAD

**Issue by crcunningham** [zeit/hyper#1149]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 14.04
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Vanilla
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Secondary/Right clicking using two fingers on my laptops (Dell XPS-13) causes a paste action. I'm also unable to use CTRL+C, CTRL+V, etc. because pressing control removes selection from the text. Using a mouse to right click is a no-op and no menu is displayed.

**Comment by ExcaliburZero** [comment]
I am having a similar issue as well on Ubuntu 16.04.1 LTS.

When I right click it pastes text. I can paste text using `Ctrl+ V` and `Ctrl + Shift + V`, however pressing `Ctrl` clears out the selection, so I cannot copy text using `Ctrl+ C` or `Ctrl + Shift + C`.

I am also using version 1.0.0 and the default config file.

**Comment by ppot** [comment]
The clearing is fixed in: #1218

**Comment by ExcaliburZero** [comment]
I have tried out the master branch at c7f195ba015fd55d1883feb5023d388d34b4a97c and the issue still persists on Ubuntu Linux at least.

**Comment by ppot** [comment]
@ExcaliburZero The `keyboard` actions or the click?

**Comment by ExcaliburZero** [comment]
@ppot 

When I right click, it pastes the text in the clipboard and loses the current selection. When I press `Ctrl + v` or `Ctlr + Shift + v` nothing happens (this is new behavior). Whenever I highlight text and press `Ctrl` it loses the current selection.

Dev version, default config file.
