### ISSUE TITLE
Emojis break Tmux display

### ISSUE THREAD

**Issue by also** [zeit/hyper#1179]
- **OS version and name**: macOS Sierra 10.12.1 (16B2555)
- **Hyper.app version**: 1.0.0 (1.0.0.1303)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/also/1ac08ef0ec74bd7200d0b7f7fdf161c4 (created by Hyper 1.0.0 and not modified.
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue

Emoji characters seem to effect the entire line, shifting characters out of alignment. This causes problems with Tmux panes to the right.

![screen recording 2016-12-13 at 12 02 pm](https://cloud.githubusercontent.com/assets/15624/21150202/2318cd12-c12c-11e6-80b4-b72bf99de43e.gif)

**Comment by dotcypress** [comment]
Fixed in https://github.com/zeit/hyper/pull/1111 😎

**Comment by flybayer** [comment]
#1111 did not fix this for me.

Also, I think this is a duplicate of #938

**Comment by pguth** [comment]
Also [`fishshell`](https://fishshell.com/) breaks:

<img width="191" alt="screen shot 2017-01-22 at 18 35 29" src="https://cloud.githubusercontent.com/assets/85259/22184444/de3bcf08-e0d1-11e6-9142-dbc88b333ae1.png">

**Comment by mojoaxel** [comment]
I have a similar issue with emojis. They break my layout in Hyper version 1.3.3l@1.3.1 on linux.
![image](https://user-images.githubusercontent.com/600565/27768274-5dd9b7c8-5f0f-11e7-95a4-618508fa7cff.png)

@also I would recommend updating the issue-title to something more generic.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by mojoaxel** [comment]
Looks like this is fixed with v2 :tada:

**Comment by maturanomx** [comment]
I'm having this issue with version `2.1.0-canary.2 (stable)`
![capture](https://user-images.githubusercontent.com/5768813/48154046-4c1c7680-e28d-11e8-92af-f564c0e64324.PNG)

Did I miss something? 🤔
