### ISSUE TITLE
Issues with plugins on Hyper 1.2.0 & 1.2.1

### ISSUE THREAD

**Issue by henrikdahl** [zeit/hyper#1513]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `10.12.3 macOS Sierra`
- **Hyper.app version**: `1.2.1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: `Default`
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: `N/A`
- **The issue is reproducible in vanilla Hyper.app**:  `Is Vanilla`

## Issue
Getting `Error updating plugins.` even without any plugins. It says to check for `~/.hyper_plugins/npm-debug.log` but no such file exists.

Seems to be having issues with downloading plugins as well. Getting `Plugin "name" failed to load (Cannot find module '/Users/henrik/.hyper_plugins/node_modules/name')`

Tried installing fresh, simply reinstalling as well. Still remains.

**Comment by RudyBermudez** [comment]
I am having the exact same problem. Also for some reason the update does not play nice with the 'hyperborder' plugin

**Comment by henrikdahl** [comment]
@RudyBermudez your issue with `hyperborder` should be fixed on `1.2.1`

**Comment by rauchg** [comment]
Should be good in 1.2.1 right @henrikdahl ? 🙏

**Comment by RudyBermudez** [comment]
Unfortunately not. I am on 1.2.1 and I am still Getting an Error when updating plugins. even without any plugins. It says to check for ~/.hyper_plugins/npm-debug.log but no such file exists.

**Comment by henrikdahl** [comment]
@rauchg It's unrelated to the CSS naming, seems to be an npm issue. Not sure what was changed between 1.1.0 and 1.2.0. Remains on 1.2.1 ✌️

**Comment by henrikdahl** [comment]
@RudyBermudez setting your shell of choice in config should temporarily fix the issue for you until/if my PR is merged ✌️

**Comment by aneira92** [comment]
I am having the same problem.

**Comment by srl295** [comment]
i think it's a dup of #312 also.

**Comment by henrikdahl** [comment]
@srl295 Unlikely since the commit that caused it is only 26 days old ✌️https://github.com/zeit/hyper/commit/993b8f6833bffe75032e9f161fd17bed0c98ed73

**Comment by srl295** [comment]
@henrikdahl I saw that, but maybe it fixed the old issue…   perhaps more precisely:  "If you see the symptoms of #312, you might actually be hitting #1513 which is fixed in #1516" How's that?

**Comment by johnlindquist** [comment]
Fresh install, I set my shell to 
```shell: 'C:\\Windows\\System32\\bash.exe',```
still seeing this.

**Comment by henrikdahl** [comment]
@johnlindquist It hasn't been released yet.

**Comment by gsklee** [comment]
@henrikdahl @rauchg Unless there is some good reason, I'd suggest rolling this fix out ASAP because this bug is showing up for everyone; new users will see this error the first moment they opening up this fleshly installed app and potentially being put off.

**Comment by joshbuchea** [comment]
As @henrikdahl mentioned, a temporary fix is to set your shell of choice in the config file: `hyper.js`. I use Zsh so I set mine to `shell: 'zsh'` and all is well 👍

**Comment by indexofrefraction** [comment]
i set the shell to /bin/bash and it fixed the plugin error, too.
maybe just any entry in shell works (?)

**Comment by fshequin** [comment]
I was having similar problems and explicitly setting my shell in .hyper.js to /bin/bash fixed the startup error about plugins not updating....

**Comment by Zx-EvM** [comment]
I use Windows 10 Build 14393.693 and Hyper 1.2.1 and `shell: 'C:\\Windows\\System32\\cmd.exe',` in `.hyper.js` config file fix startup error http://imgur.com/a/e1cid `Error updating plugins`

**Comment by thasmo** [comment]
Can confirm what @Zx-EvM said. Using `C:\\Windows\\System32\\bash.exe` fails with the mentioned plugin-error message.

**Comment by Zx-EvM** [comment]
@thasmo it's because hyper terminal installed on Windows and Linux Subsystem work like Linux PC. To change hyper theme or install plugin you need to change shell to `C:\\Windows\\System32\\cmd.exe` and change what you need. Then again use `C:\\Windows\\System32\\bash.exe`

**Comment by math2001** [comment]
So, there's no solution yet? I tried set `shell` to `C:/Program Files/Git/bin/bash.exe`, but I still got the same problem... (BTW, I need to `npm install ...` the plugins myself, it doesn't work by just adding it to the list of `plugins`)

**Comment by math2001** [comment]
Hum... If we run `hyper` from a terminal (kind of weird, I expected a `hyper.exe`, but you have to run `path\to\hyper\Update.exe --processStart "Hyper.exe"`, but anyway) to get the output:

```
~
$ hyper

plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file://C:\Users\Home\AppData\Local\hyper\app-1.2.1\resources\app\index.html
Checking for notification messages
No matching notification messages
Error: Command failed: npm prune && npm install --production
/usr/bin/bash: Files/Git/bin/bash.exe: No such file or directory

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.
```

`npm` fails since there **is a space in the `shell` value**. (`shell: 'C:/Program Files/Git/bin/bash.exe',`)

## So, the solution?

Is to create a `bat` file (since I'm on windows) which *doesn't have any spaces in its path* and this file just runs what we'd usually put in the `shell` value.

So, I created `C:/Users/math/Desktop/hyper.bat`, set the content to `"C:/Program Files/Git/bin/bash.exe"
`, and I was good to go.

## The problem

Unfortunately, there's a small (but less annoying) problem: the command is displayed at the top of the terminal:

```
C:\Users\Home>"C:/Program Files/Git/bin/bash.exe"

~
$
```

## The solution

*I thought about this solution while I was writing this message* 😄

just add `cls && ` at the beginning of the runner:

in  `C:/Users/math/Desktop/hyper.bat`:

```
cls && "C:/Program Files/Git/bin/bash.exe"
```

The equivalent of the `windows` `cls` is `echo -e '\\0033\\0143'`

So, hopefully that works for you too 😉

**Comment by dipaktelangre** [comment]
Does anyone really has solution/workaround for the plugins of hyper on windows 10. I like this terminal too much but cant install any plugin to it.

**Comment by dkdl** [comment]
Adding /bin/bash to the settings fixed the problem for me 👍

**Comment by math2001** [comment]
@dipaktelangre, could you run hyper *from* a cmd, and tell me what you get.

1. open the windows start menu (just press the <kbd>window</kbd> key)
2. search for hyper
3. right click it and select (`Open File Location`)
4. right click the shortcut and select (`Open file location`)
5. go into the folder called `app-xxx` (in my case `app-1.2.1`)
6. click on `hyper.exe`
7. in the top bar, in the `Home` tab, click `Copy Path`
8. <kbd>Windows+R</kbd>, type in `cmd` and hit <kbd>enter</kbd>
9. copy the output and paste it here.

**Comment by dipaktelangre** [comment]
@math2001 What you want me to past ```C:\Users\dipakt\AppData\Local\hyper\app-1.2.1``` this is path of folder where ```hyper.exe``.
![capture](https://cloud.githubusercontent.com/assets/2802393/23714059/edec7ebc-044d-11e7-93fc-533d5655ce0e.PNG)
This is output of the ```cmd```

**Comment by math2001** [comment]
😖 I forgot a step. I edited the message to add it, it's the `9`.

**Comment by dipaktelangre** [comment]
![capture](https://cloud.githubusercontent.com/assets/2802393/23738710/a6c3cefa-04c0-11e7-81dc-c82ee6b1ce83.PNG)

This is ```cmd``` output for ```hyper``` command. It open hyper terminal and start giving the plugin error notifications.

**Comment by flxw** [comment]
Thank you guys so much for fixing this on Windows <3

**Comment by rauchg** [comment]
Thank you for your patience!

**Comment by HowardStark** [comment]
As far as I can tell, this is still an issue. Installed nodejs and verified that npm is working correctly, ran `npm i` in the `.hyper_plugins` directory, and restarted. There are no spaces in the shell path (`C:\\Windows\\System32\\bash.exe`), so that fix above is moot.

**Comment by lebilly** [comment]
Not sure if this is the same issue but I was following [#312](https://github.com/zeit/hyper/issues/312) and it still doesn't work. My plugins and everything work but this notification keeps popping up.
<img width="292" alt="capture" src="https://user-images.githubusercontent.com/9342687/30414817-35970be4-98da-11e7-8ee5-ce52e8a378cf.PNG">

I'm on Windows Build: 15063.608
Using Ubuntu on Windows
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
HyperTerm Version:  1.4.4 (Stable)
WSL Node:  v8.5.0
Windows Node: v.6.11.3

**Comment by chabou** [comment]
@lebilly Thank you for your feedback
This not exactly the same issue.
We are tracking this problem in https://github.com/zeit/hyper/issues/2173
