### ISSUE TITLE
Hyper config 'module' is undefined

### ISSUE THREAD

**Issue by Meadowcottage** [zeit/hyper#1810]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10-64 Bit (Creators Update)
- **Hyper.app version**: 1.3.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/Meadowcottage/558b4e184ee98e0fee223b7678abcba0)
- **The issue is reproducible in vanilla Hyper.app**: Yes. Issue only current in version 1.3.2+.

## Issue
Control+Comma (Shortcut to open .hyper.js file) in version 1.3.2 results in the following error.
![](https://i.imgur.com/PfI0qOa.png)
Tested in prior version, 1.3.1, and the issue isn't current. Guessing an issues from the 1.3.2 update.

**Comment by DavidDeSloovere** [comment]
I got the exact same error. Fresh installation.

Hyper 1.3.2
Electron 1.4.16
win32 x64 10.0.16184

**Comment by Pyrepenol** [comment]
Same here. win 10 64-bit, Hyper 1.3.2

**Comment by andreynazarov3** [comment]
same here. win 10 64-bit

**Comment by denniseffing** [comment]
Same here, Win 10 1703 64-Bit, Hyper 1.3.3

**Comment by Szomy** [comment]
Try to set a default editor for .js files.
Windows tries to run javascript as a script.

**Comment by albinekb** [comment]
Solved in #1872

**Comment by Bandit** [comment]
I'm still getting this problem after downloading the .exe from the website. Has the installer not been updated perhaps?

**Comment by ppot** [comment]
Yes, it will be in the next release! Not released yet

**Comment by Positive07** [comment]
Note that it will open the file with Notepad (not your default editor, whatever it may be)

**Comment by AmirinNS** [comment]
I just change the default application for .js file. For example, I am using Sublime for editing .js file instead of using Microsoft Script. It should work by this way 
![snap35](https://user-images.githubusercontent.com/23518901/28743783-e38efd9e-7484-11e7-89de-b9da273a093e.PNG)

**Comment by isseiler** [comment]
This is still an issue:

![image](https://user-images.githubusercontent.com/25071166/29696857-59bae5c0-8900-11e7-9087-b2c1f338f5b7.png)

**Comment by mlynch** [comment]
Can confirm this is still an issue with the current Hyper. Tried to open Preferences and received the exact same issue as @isseiler

**Comment by MarcoPeraza** [comment]
This is still an issue for me. Hyper version 1.4.8 on Windows build 17101.

**Comment by thuld** [comment]
Reproducible with my machine.
