### ISSUE TITLE
Using "clear" command doesn't clear the screen buffer

### ISSUE THREAD

**Issue by axelitus** [zeit/hyper#2093]
Using the clear command doesn't clear the screen buffer.

This happens in both these situations:
- Using the clear command through linux commands added to the path with git installation.
- Connected to a linux vagrant machine through ssh

Using "cls" command (while in DOS prompt) works fine.

Screenshot:
![2017-08-17_10h41_06](https://user-images.githubusercontent.com/732441/29420787-aa400f70-8338-11e7-9c35-1dc3eb47c21c.png)

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by SHewitt95** [comment]
I ran into a similar issue on a similar system setup. [This comment](https://github.com/zeit/hyper/issues/1559#issuecomment-281763405) and [this comment](https://github.com/zeit/hyper/issues/1559#issuecomment-282575163) resolved the issue for me.

**Comment by axelitus** [comment]
I had tried your suggestion and it worked (with both, cygwin and msys).
```
set TERM=cygwin
clear
```

I tried setting the Environment Variable so it would be fixed and every time I opened Hyper it would have it configured. It does not work, every time I open the console it has TERM=xterm-256color set, and I don't know where it's being set.
![2017-08-21_13h35_34](https://user-images.githubusercontent.com/732441/29533069-bbb046d6-8675-11e7-9777-e593206a3aed.png)

I've tried looking in %USERPROFILE%\AppData\Local\lxss\home\%USER%\.bashrc which is the location of the .bashrc file for "Bash on Ubuntu on Windows" without luck. any ideas? I think it would be best if Hyper added xterm-256color to the list of terms with such behavior though.

**Comment by axelitus** [comment]
Mmmmm it's strange. It looks as if Hyper is the one setting the term to xterm-256color
![2017-08-21_13h39_48](https://user-images.githubusercontent.com/732441/29533179-4e910ab2-8676-11e7-91d9-a14fe89aea4e.png)

**Comment by axelitus** [comment]
This is still an issue in version 1.4.3

I don't now the internals, but I don't know why this doesn't work, as it works fine in both CMD.exe and PowerShell.

**Comment by Magneticmagnum** [comment]
Try updating to 1.4.7.  It should be resolved now.

**Comment by axelitus** [comment]
Still not working. Trying with the new 1.4.7 and with a clean `.hyper.js` config file.

![2017-09-21_08h34_32](https://user-images.githubusercontent.com/732441/30698476-b642f74e-9ea7-11e7-904c-9636f4074820.png)

**Comment by technbuzz** [comment]
I am on version 2.0.2 but still facing this issues. BTW I am on windows and 've set hyper for bash

**Comment by esechres** [comment]
I am on version 2.0.0 (stable) and still facing the issue where 'clear' does not work.  The "shell" is set to `shell: 'C:\\Program Files\\Git\\git-cmd.exe',` and TERM is set to `xterm-color`.  While setting TERM to `cygwin` allows 'clear' to work, it causes problems with vi/vim.

**Comment by tiagoboeing** [comment]
Same problem...

![image](https://user-images.githubusercontent.com/3449932/48308320-33d88000-e549-11e8-9ea5-25b1ab85ce89.png)

**Comment by Ben2015-2015** [comment]
1. echo $SHELL to check what type of shell
2. follow this https://kb.iu.edu/d/acpy

**Comment by tracker1** [comment]
`hyper 2.1.1 stable`

Windows, Git For Windows's Bash... Clear and `\022[2J` both fail to work properly in Hyper.

from Configuration
```
    shell: 'C:\\Program Files\\Git\\bin\\bash.exe',
    shellArgs: ['-i'],
    env: {
      CHERE_INVOKING: "1",
      TERM: "cygwin",
    },
```

Setting TERM in my `~/.profile` to cygwin works, but the configuration option doesn't seem to be tacking for env.

@tiagoboeing - when I use `CTRL + SHIFT + K` it mostly clears, but the active line still has text clobbering the current line and as soon as `ENTER` is pressed the clobbered screen re-appears.

**Comment by tiagoboeing** [comment]
This problem is not only for Hyper, when you are using Git Bash for Windows and integrate in a terminal external, bugs happens.

I'm using Terminus and `CTRL + SHIFT + K` have same problem.
