### ISSUE TITLE
Hyper crashes whilst idle after update

### ISSUE THREAD

**Issue by CodeTheory** [zeit/hyper#2168]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS 10.12.6 (16G29)
- **Hyper.app version**: 1.4.2 (Failed to update to 1.4.3)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/CodeTheory/a3a770ed8bfb593e87f0dbeb378b737f
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Couldn't test on Vanilla since the steps to reproduce are odd

## Issue
![image](https://user-images.githubusercontent.com/1695613/30024225-b0a7b42c-916a-11e7-9f60-903c077966b9.png)
<details>
<summary>Error text</summary>
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Object has been destroyed
at notify (/Applications/Hyper.app/Contents/Resources/app.asar/notify.js:36:8)
at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:86:11)
at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:43:7)
at cp.exec.err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:28:13)
at ChildProcess.exithandler (child_process.js:214:7)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:885:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
</details>

Here's how I got this:
- Opened hyper yesterday, idle until this morning
- Update notification for 1.4.3, clicked to restart
- Didn't open Hyper again and about 30 minutes later, get that error since the icon was bouncing I noticed it
- Hyper didn't update to 1.4.3

**Comment by chabou** [comment]
My guess: Update has failed, leaving Hyper running without any window. 30mn later, hyper check for an update and found one. Want to notify but no more window.

**Comment by badlands** [comment]
Still happens on version 1.4.3

- [X] I am on the latest Hyper.app version
- [X] I have searched the issues of this repo and believe that this is not a duplicate

- OS version and name: Mac OS 10.12.6 (16G29)
- Hyper.app version: 1.4.3
- Link of a Gist with the contents of your .hyper.js: https://gist.github.com/badlands/6f84733bed5846a705ff77c65b3c4a39
- Relevant information from devtools (CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere): N/A
- The issue is reproducible in vanilla Hyper.app: Couldn't test on Vanilla since the steps to reproduce are odd

**Here's how I got this**

Launched Hyper, performed simple actions (vim, ls, ...), left it open doing nothing.

**Problem Report**

```
Process:               Hyper [21559]
Path:                  /Applications/Hyper.app/Contents/MacOS/Hyper
Identifier:            co.zeit.hyper
Version:               1.4.3 (1.4.3.88)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Hyper [21559]
User ID:               501

Date/Time:             2017-09-06 12:19:01.219 +0200
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        F63DBDE0-0489-1986-FF76-7A0335449587

Sleep/Wake UUID:       319CB022-2990-4726-83F5-69B69DA8A22D

Time Awake Since Boot: 64000 seconds
Time Since Wake:       2800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000028694026bec0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x28694026bec0:
    Memory Tag 255         0000258f47540000-0000258f47542000 [    8K] ---/rwx SM=NUL  
--> 
    Memory Tag 255         00002982a7d00000-00002982a7d80000 [  512K] rw-/rwx SM=PRV  

Application Specific Information:
objc_msgSend() selector name: _fastCStringContents:


Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fffdc75005d objc_msgSend + 29
```

**Comment by revelt** [comment]
This morning I found my Hyper crashed when left overnight. I'll be using iTerm2 from now on.

**Comment by chabou** [comment]
Electron was upgraded in master and certainly have a fix for this:
https://github.com/electron/electron/pull/10099

You can use `master` release or wait for our next release 🔜

**Comment by chabou** [comment]
Should be fixed by #2193

**Comment by chabou** [comment]
@badlands 
v1.4.4 just released.
I hope that it will resolve your crash issue (but this not the subject of this issue)
Please update https://github.com/zeit/hyper/issues/2152 if your issue is not resolved

**Comment by asotog** [comment]
I'm on 1.4.6 still seeing this issue happening

<img width="435" alt="screen shot 2017-10-02 at 2 05 59 pm" src="https://user-images.githubusercontent.com/813023/31096972-fe874d8a-a77a-11e7-8d5a-cfb9b7551554.png">

**Version details:**
Hyper 1.4.6 (stable)

Plugins Installed:
- hypercwd (1.1.1),
- hyperterm-tabs (1.3.5),
- hyper-statusline (1.7.3),
-   hyper-search (0.0.6),
-   hyperterm-visor (0.3.4),
-   hyperterm-cobalt2-theme (1.0.3),
-   hyperlinks (0.5.0)

**Comment by Stanzilla** [comment]
@EvanDarwin release or canary version?

**Comment by CatherineHenry** [comment]
This happens to me as well, W10. I usually don't actually get a stack trace, my window just becomes inaccessible. I am able to get a similar stack trace when I attempt to Update manually. However, hyper becomes inaccessible after a few hours, consistently. 

I'm running version 1.4.8 stable
and have the following plugins: 'hyperterm-paste' (1.1.2), 'hyperlinks' (0.5.0), 'hyperterm-overlay' (0.4.0), 'hyperterm-cursor' (0.0.3), 'hyper-seashells' (1.0.0)

**Comment by markau** [comment]
I have just started getting this issue over the past two weeks or so. It occurs after locking the Windows PC for a period of time (certain to occur overnight). v2.1.2
