### ISSUE TITLE
Gradle build output is messed up

### ISSUE THREAD

**Issue by NomNuggetNom** [zeit/hyper#2391]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64 Build 15063
- **Hyper.app version**: 2.0.4 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/NomNuggetNom/b71dcd3984117c1a949315339b48f03b
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When issuing a build with gradle, it seems to try and detect what colors to show. Whatever it decides upon, the terminal can't handle it properly. Here's a sample screenshot:
![Sample](http://nom.codes/i/r/ETmNe)

As you can see, other colors work in the console, but whatever Gradle is trying to do, it doesn't work. I'm not sure if this is a Gradle issue, but this DOES NOT happen in the native terminal that comes with git bash. Comparison:

![Bash](http://nom.codes/i/r/oaLuv)

**Comment by NomNuggetNom** [comment]
@albinekb Any more info I can provide for this?

**Comment by albinekb** [comment]
Don't think so, I can take a look soon if I can reproduce 👍

**Comment by NomNuggetNom** [comment]
@albinekb Any luck? Happy to try and help if I can!

**Comment by NomNuggetNom** [comment]
I fixed this myself after some annoying debugging. Hyper sets the `TERM` environment to `xterm-256`, which changes the way Gradle does the output. In my config I set:
```
env: {
   TERM: 'cygwin'
}
```

I'm not sure who's end this problem originates on.

**Comment by stevenjlho** [comment]
@NomNuggetNom It works, thank you.

**Comment by kevinwtenweerde** [comment]
I still experience this issue when running a gradlew bootRun command.
V2.1.0-canary.2. Tried to set the env to cygwin. No difference for me.
