### ISSUE TITLE
Terminal not using full width

### ISSUE THREAD

**Issue by cmeiklejohn** [zeit/hyper#2613]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
(could not find a duplicate of an open issue)

- **OS version and name**: Windows 10
- **Hyper.app version**: Latest Canary Release
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cmeiklejohn/74462ca5354401ffaf8f476d3a796b80
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 
Not using any plugins in my configuration.

## Issue

See image.  No matter what configuration I set the width to, the application running inside of the terminal is not using the full width.  Here's an example of `htop` and `vim`.

![not-full-width](https://user-images.githubusercontent.com/44939/34967987-6b311f72-fa34-11e7-80c7-6ce686c6fbbc.PNG)

**Comment by cmeiklejohn** [comment]
I removed the `.hyper.js` and the `.hyper_plugins` directories -- didn't resolve anything.  I did a reinstall over the existing installation, and it seemed to resolve the issue.  However, as soon as I made a single change to the configuration -- such as moving the default shell to bash.exe / cmd.exe -- the problem came back.

**Comment by cmeiklejohn** [comment]
However, when I *don't* delete the configuration, and then reinstall over the existing installation, the settings remain and the problem goes away.

**Comment by cmeiklejohn** [comment]
I was able to reproduce the problem again by making a change to the configuration to introduce the problem, and a reinstall over the existing implementation resolves the issue, while preserving my configuration changes.

**Comment by chabou** [comment]
Should be fixed by https://github.com/zeit/hyper/pull/2594

**Comment by cmeiklejohn** [comment]
So, my understanding is the latest canary build should fix this?

**Comment by cmeiklejohn** [comment]
I tried switching to the canary build and I'm still experiencing the issue.  Do I have to wait for a new 'canary' build to be created / shipped?

**Comment by chabou** [comment]
Yes 🔜

**Comment by chabou** [comment]
Available on [2.0.0-canary.10](https://github.com/zeit/hyper/releases/tag/2.0.0-canary.10)

**Comment by cmeiklejohn** [comment]
Great, that seemed to fix the issue.  It's not full width still, but I'm at least seeing the fix from #2594.

**Comment by tiferrei** [comment]
Hi, I think I might be having a similar issue on macOS 10.13.4, Hyper 2.0.0-canary.14 (canary).
![screen shot 2018-02-28 at 23 26 54](https://user-images.githubusercontent.com/8849915/36818886-fdf5f3ec-1cde-11e8-80ed-f5dc89020054.png)
