### ISSUE TITLE
Input Very Laggy After Update to 2.0

### ISSUE THREAD

**Issue by BrysonR** [zeit/hyper#2838]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Anniversary Edition
- **Hyper.app version**: 2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/BrysonR/d37a699fced1f16ea451e3015344fdd0
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
`total init time 515.8100000000002
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 371ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 357ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 354ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 399ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 394ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 404ms
bundle.js:1 [Violation] 'requestAnimationFrame' handler took 373ms`

- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Since upgrading to 2.0 a few minutes ago any prompt input is incredibly laggy. Looking at the dev tools console it looks like `requestAnimationFrame` handler is taking between 300-513ms to respond from a few test keystrokes I did for the purpose of this issue.

**Comment by jeyj0** [comment]
I just noticed that clearing the console window using CTRL+L helps.

**Comment by chabou** [comment]
Maybe related to https://github.com/electron/electron/issues/11051

**Comment by MartinMuzatko** [comment]
This is very embarrassing, considering the effort you put into 2.0
After downgrading to https://github.com/zeit/hyper/releases/tag/1.4.8 everything is fine again (or at least back to the normal level of slowness ;) ).

**Comment by BrysonR** [comment]
Only issue is that it constantly tries to update and there's no auto-update toggle off so if I accidentally restart Hyper or my computer I have to go through the process of uninstall => reinstall => pin to taskbar => properties => advanced => check run as administrator. Needless to say, it's tedious.

**Comment by BrysonR** [comment]
I will also note I just tested the macOS version and it seems to not be effected.

**Comment by ranglust** [comment]
+1 on this one.
after upgrading to 2.0.0 (barebone, no plugins) the console became so slow its unusable.

**Comment by danmindru** [comment]
Can confirm, it's unusable on Windows 10 anniversary. 
- [x] no plugins enabled
- [x] no console errors

Seems to get exponentially slower as the number of displayed lines grows... 
Quick look into dev tools show 'drawImage' to be slow.

![hyper-2](https://user-images.githubusercontent.com/1515742/38859775-0ab8a9f6-422f-11e8-904d-d6257be84855.png)

**Comment by jeyj0** [comment]
Seems to have to do something with displaying fonts. If I have time later I'll investigate further, but I noticed that changing fonts can improve performance.

**Comment by simonhaenisch** [comment]
I have the same input lag issue when using the _Source Code Pro_ font (on a Macbook Pro 2011)... can confirm that the input lag goes away when I use the default `fontFamily` setting.

I also noticed that rendering output is really slow (regardless of the used font). I screen-recorded running `ls -alh` in my home folder in a newly created window. It took `0.95s` for the first output to render and `1.8s` till the prompt was available again.

**Comment by albinekb** [comment]
If you change the font and restart the app, is there still input lag? Xterm has an advanced character man to speed up rendering, maybe it's not getting re-initialized correctly after changing font @simonhaenisch

**Comment by simonhaenisch** [comment]
@albinekb I tried restarting with a custom font, in the first prompt it seemed fine... but after printing something to the output (like listing a directory), the lag came back. Then I tried disabling the custom font and restarted and realized that the lag is actually the same.

So it doesn't seem to be related to the font really, but only to how many characters have been printed already. The more characters, the slower it gets. But what bugs me even more is how long it takes to render the output of a simple command like listing a directory.

**Comment by albinekb** [comment]
Can you try with completely vanilla `.hyper.js` (just move your old one and restart hyper so you get the vanilla one), and then just change the font? Also try changing your shell to rule out any weirdness. 

It sounds like something is making the character map to not be applied, it could be that you have some transparency differences in your config or something, hard to debug so try to rule out everything.

**Comment by idoru78** [comment]
@albinekb I've just done this and it made no difference at all. Even the first `dir` command takes and age to display the results.

**Comment by simonhaenisch** [comment]
@albinekb I used app cleaner to delete any hyper related config and cache files, and deleted `~/.hyper.js` and `~/.hyper_plugins`. Didn't help.

I narrowed it down though, it's related to the amount of characters being visible. When I list my directory, the input lag is there, but if I just hit enter a few times to move it out of view, then the lag is gone again (same as `clear` or <kbd>Cmd</kbd>+<kbd>K</kbd>). The more characters there are visible, the more lag there is.

**Comment by AustinTruex68** [comment]
Having the same issue, huge latency, very hard to use. - Windows 10, no plugins, just plain ol hyper. 
Tested on my Mac, and it had no issues.

**Comment by bpeab** [comment]
I actually have the same issues with macOS High Sierra.

**Comment by Tyriar** [comment]
This is probably https://github.com/electron/electron/issues/11051, try running `hyper --ignore-gpu-blacklist`. Note that you will need to run this against the actual hyper executable, not the CLI script. For Windows this is probably `Hyper.exe`, on Linux `/opt/Hyper/hyper`.

See https://github.com/zeit/hyper/issues/2833#issuecomment-381689454, https://github.com/zeit/hyper/issues/2839

**Comment by Tyriar** [comment]
Hyper may actually have the liberty of just always running `--ignore-gpu-blacklist` *unless* `--disable-gpu` is specified? I haven't explored doing this for VS Code as the terminal is an optional component; the editor runs without canvas.

You may also want to explore updating to Electron 2 asap which will improve the situation (not fully resolve https://github.com/electron/electron/issues/12042). It's currently in beta but I expect it to be stable in the coming weeks: https://github.com/electron/electron/releases/tag/v2.0.0-beta.7

**Comment by gleeds** [comment]
`--ignore-gpu-blacklist` totally fixes it for me even though my windows machine only had Intel HD Graphics.

**Comment by bpeab** [comment]
Argument `--ignore-gpu-blacklist` also does it for me.

**Comment by simonhaenisch** [comment]
I can confirm that, too (on macOS).

```
open /Applications/Hyper.app --args --ignore-gpu-blacklist
```

and everything is smooth.

**Comment by travisbotello** [comment]
Confirmed. Works for me on macOS.

`open /Applications/Hyper.app --args --ignore-gpu-blacklist`

**Comment by bjaskj** [comment]
I can confirm that  --args --ignore-gpu-blacklist in Windows 10 made it run fast!

**Comment by chabou** [comment]
@Tyriar Thank you so much for your insights. I'll study how to always running `--ignore-gpu-blacklist` and the potential downsides.

**Comment by chabou** [comment]
I built a macOS (dmg) canary version with `ignore-gpu-blacklist` flag set by default: https://file-uwnqivoumn.now.sh

@bpeab @simonhaenisch @travisbotello Can you confirm me that this version fixes your issue? (Do not replace your installed version, this one is not signed and auto-update couldn't work)

**Comment by olivier-w** [comment]
@chabou Thanks! Your version also fixes the lag.

**Comment by bpeab** [comment]
@chabou Same here. It works great. ✌🏼

**Comment by chabou** [comment]
Landed in our [v2.1.0-canary.1](https://github.com/zeit/hyper/releases/tag/2.1.0-canary.1) release 🎉

**Comment by thejamespower** [comment]
I'm still getting 300-400ms animation frames on Windows 7, running v2.1.0-canary.1. Any suggestions? Hyper is still completely unusable for me in its current state and I can't stand any other terminal on Windows :sob:

**Comment by BrysonR** [comment]
Just installed v2.1.0-canary.1 and it seems to have fixed the issue. You guys rock!

**Comment by bpeab** [comment]
Same for me here. Thanks ✌🏼

**Comment by olivier-w** [comment]
Is there a way to disable pushed updates? It keep installing v2.0.0 and I have to reinstall v2.1.0-canary.1 over again  😕

**Comment by simonhaenisch** [comment]
@olivier-w why don't you change the [`updateChannel`](https://hyper.is/#cfg) to `'canary'`?

**Comment by olivier-w** [comment]
@simonhaenisch Thank you! I totally missed that  🙌

**Comment by ranglust** [comment]
the --ignore-gpu-blacklist seemed to solve the problem

**Comment by albinekb** [comment]
@heynemann I recommend you to open a new issue with steps to reproduce, then we can take a closer look at your issue, this issue has been resolved in latest canary with `--ignore-gpu-blacklist`, your must be something else 👍

**Comment by albinekb** [comment]
@jaxspades you need to use the canary version, that is not possible in 2.0.0 stable, read about using canary here: https://zeit.co/blog/canary#hyper

**Comment by jaxspades** [comment]
Thanks! I switched to canary and I'm still having an issue with lag. It seems to take a couple hundred milliseconds for each keystroke, and a few seconds for `ls` on a moderate sized folder. Do I need to do something else with my setup, other than using `cmd` to open "canary" version `hyper` with `--args --ignore-gpu-blacklist`?

**Comment by chabou** [comment]
@jaxspades you don't have to add args anymore with our `2.1.0-canary.1`. Please verify your version with about box. Thank you for your feedback 🙏

**Comment by BrysonR** [comment]
Same here. It stopped for a bit and now started again and very very laggy. I switched back to 1.4.8 as a result

**Comment by AustinTruex68** [comment]
Same with me, switching back to older version in the mean time...

**Comment by albinekb** [comment]
@BrysonR @AustinTruex68 have you tried the canary build which skips the GPU blacklist and gives back the performance (GPU accelerated canvas, blacklist is for webGL bugs, we do not use webGL)

**Comment by BrysonR** [comment]
I was on 2.1.0 Canary when I started experiencing again and downgraded.

**Comment by jaxspades** [comment]
@chabou, @albinekb I'm using `2.1.0-canary.1` now, and still experiencing input lag on Windows 7.

**Comment by kbmakevin** [comment]
I just upgraded to 2.1.0-canary.1 and although I noticed a slight improvement, the input lag is still happening. I am using Windows 10

**Comment by AustinTruex68** [comment]
Same here on Windows 10, upgraded to 2.1.0-canary.1 and had slight improvement, but still pretty bad input lag. Currently using 1.4.7 and it's doing fine.

**Comment by alexqhj** [comment]
Same issue windows 10. I even had Version 2.0.0 stable and upgraded after I noticed the issues. Neither version worked properly. `--args --ignore-gpu-blacklist` also did nothing for me

**Comment by xster** [comment]
Same here, tried 2.0.0 and 2.1.0-canary and opening some file in emacs and holding up or down is super painful:

![screen shot 2018-05-20 at 1 56 47 am](https://user-images.githubusercontent.com/156888/40277286-2b84cffa-5bd1-11e8-9a98-4cdc69bc1ead.png)

**Comment by cmeiklejohn** [comment]
```2.1.0-canary.1``` made it usable again for me.

**Comment by albinekb** [comment]
@alexqhj try the canary, it's using GPU rendering for the canvas 👍

**Comment by alexqhj** [comment]
I probably didn't make it clear enough. I had the issue on both 2.0.0 stable and canary. What's weird is that 2.0 worked fine for months until one day it just didn't. Probably a windows update.

As of now, hyper is useless for me. I might jump down to 1.x and see if that works.

**Comment by BrysonR** [comment]
1.4.8 #OlFaithful

**Comment by jaxspades** [comment]
1.4.8 also resolved the issue for me.

**Comment by offero** [comment]
Same here. Jus typing in vim. Perf screenshot attached.
![image](https://user-images.githubusercontent.com/4681330/40879993-873ac128-6677-11e8-99d3-0b0578de2e23.png)

**Comment by mtsiedent** [comment]
For me, the canary build solved it as well... Debian based Linux

**Comment by pielco11** [comment]
> $ hyper -v

![immagine](https://user-images.githubusercontent.com/17363750/41836847-2ff88c00-785c-11e8-82fc-85522c58d70b.png)

> Impossible to open the shared object, file or directory does not exist

Ubuntu 16.04, no issues with 2.1.0-canary.1

**Comment by AriPal** [comment]
@sebinsua, how to run this on Linux. 

`/opt/Hyper/hyper --ignore-gpu-blacklist`

**Comment by joshporter1** [comment]
Still having this issue with 2.1.0-canary2. Issue is most prominent when a webserver logs have printed out a few lines. And it's unusable when using tmux. I can detach from tmux and re-attach using cmder or even the standard bash terminal with zero input lag.

**Comment by BrysonR** [comment]
Does the hyper v2 leverage electron v2?

**Comment by matthewlilley** [comment]
Having this issue with the latest version using WSL + Zsh. Fine initially and a gradual slowdown until it's unusable.

**Comment by albinekb** [comment]
Not yet @BrysonR

**Comment by BrysonR** [comment]
:sad-face:

**Comment by Nidnogg** [comment]
I'm having a different albeit similar situation - running MacOS El Capitan and the input lag is there as soon as I open it. Tried the --ignore-gpublacklist fix posted here earlier to no avail. Reinstalling, and or deleting .hyper.js doesn't fix it.

**Comment by ethanent** [comment]
Yeah, was having the same issue here on macOS High Sierra. Solved by updating to 2.1.0 canary release.

**Comment by Nidnogg** [comment]
I tried following your suggestion and it finally solved the latency. However, within 5 seconds of seeing my Hyper restored, I get a popup saying version 2.0.0 is stable and it asks me to restart. Even if I do tick the X, it still downgrades and brings the latency back with it. 

I fiddled around with the .hyper.js file and this happens even after switching to the 'canary' channel. How do I stop this auto-updating?

**Comment by BrysonR** [comment]
I believe the shortcut in Start Menu and if you pin it to your taskbar use `C:\Users\<UserName>\AppData\Local\hyper\Update.exe` as the Target. I switched mine to `C:\Users\<UserName>\AppData\Local\hyper\Hyper.exe` so it doesn't try and update on start every time. 

@Nidnogg  Hope that helps

**Comment by BrysonR** [comment]
I just got a new box and installed v2 canary and still noticed some lag when comparing it to cmd. I think lag might be more noticeable given I'm a Mavis Beacon prodigy and type faster than the average user...probably.

**Comment by Pooya-Tolideh** [comment]
I'm on Windows 10 and using Bash & ZSH. After adding `canary` to the `.hyper.js` speed went up noticeably.

after doing so, I suggest closing and re-opening hyper from the main folder (mine is inside AppData) and wait for it to give a "restart" prompt.

**Comment by YoungElPaso** [comment]
Canary 2.1 works well on Ubuntu 17.10

**Comment by hammypants** [comment]
Chiming in that moving from 2.0 stable on latest Win 10 to the latest Canary fixed all input lag for me .

**Comment by dbpolito** [comment]
Canary 2.1 on Mac Mojave is still laggy here.

**Comment by bpeab** [comment]
Same here. Canary 2.1 on Mac with Mojave. Hyper is unusable.

**Comment by bpeab** [comment]
I take back what I said. It works perfectly fine on the last Mojave version (Macbook Pro Retina Mid-2012). It was coming from else where, not related to Hyper itself.

**Comment by nnnnicholas** [comment]
I, too, am experiencing lots of lag when typing in 2.0.0 for Windows 10.

**Comment by mvenaas** [comment]
Can confirm heavy input lag in v2.0 on windows enterprise. Using pre-release canary 2.1 worked wonders.

**Comment by shawnolson-fp** [comment]
Canary 2.1.0-canary.2 (stable) working perfectly on Windows 10
[https://github.com/zeit/hyper/releases](url)

**Comment by Metrakit** [comment]
It's really slow too on macOS Mojave. Im using iTerm for a long time and I'm trying to switch to Hyper but it's really slow when I'm typing. This issue will be fixed ?

**Comment by srchulo** [comment]
I did the Windows protection stuff mentioned above, but I'm still getting this locally and when I SSH. I also see this issue on my Mac.

**Comment by Matt-Gleich** [comment]
I am having latency issues as well. I have a feeling that it is hardware due to the fact that it is fine on my iMac but really slow on my MacBook.

**Comment by Stanzilla** [comment]
Please make a new issue if this still happens with recent canary CI builds
