### ISSUE TITLE
When I open the hyper app, its just a black screen, it was just working yesterday. tried restarting

### ISSUE THREAD

**Issue by jordandev23** [zeit/hyper#2845]
- [ ] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** win32 x64 10.0.16299
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "C:\\Program Files\\git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "cygwin"
  },
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [
    "hyperterm-material",
    "hyperpower",
    "hypercwd",
    "hyperborder",
    "hyperterm-tab-icons",
    "hyper-blink",
    "hyperterm-cursor",
    "hyper-transparent",
    "hyperterm-tabs"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by xoagop** [comment]
Does it work correctly if you disable your plugins? I had `hyperborder` installed and disabling it fixed the issue for me.

**Comment by andeersg** [comment]
I also got it working again by disabling `hyperborder`.

**Comment by nagman** [comment]
Same bug here and `hyperborder` was the cause.

**Comment by nfmontenegro** [comment]
same, all my screen is black 😔

**Comment by pash90** [comment]
@xoagop Do you have any idea why `hyperborder` doesn't work with new version of Hyper? I have to keep downgrading to 1.4.8 everyday so I can keep using my plugins

**Comment by albinekb** [comment]
@pash90 follow `hyperborder` issue at https://github.com/webmatze/hyperborder/issues/43

**Comment by jordandev23** [comment]
Hyperborder was the issue for me! Thank you for all the responses! I just
disabled and it and reenabled it as of now and that seems to have fixed it.

**Comment by lacymorrow** [comment]
@xoagop @jordandev23 @andeersg @nagman @adaolima @albinekb @nfmontenegro 

New plugin `hyper2-border` has been created for Hyper2, https://github.com/lacymorrow/hyper2-border

You can install it by adding it to your `.hyper.js` configuration:

`plugins: ['hyper2-border']`

**Comment by Xapphire13** [comment]
@lacymorrow, may I ask why you didn't contribute to the existing plugin rather than publish a new fork?

**Comment by lacymorrow** [comment]
@Xapphire13 A few reasons, I didn't start the plugin as a fork, but I ended up using heavily from @webmatze and wanted to credit him.

I don't intend to support any of the features or write any tests like the original (although I love Ava) and I didn't want to mangle the repo in a PR. The only reason I included the random color feature is due to the wonderfully reusable code by the original author.

I also don't think this is backwards compatible with Hyper1, I wanted it to be searchable on it's own, and Now requires unique NPM package names for plugins.

**Comment by Xapphire13** [comment]
That makes sense. I just wondered if you were planning on taking it in a new direction or something =]

**Comment by webmatze** [comment]
I just released version 1.0.1 of [hyperborder](https://github.com/webmatze/hyperborder)!

It should fix the problems with Hyper v2.x.x and is backward compatible with older versions.

Would be great if you could upgrade and report any problems.

**Comment by Stanzilla** [comment]
Go update your plugins, everyone. If there is no update, disable for the time being. We are working towards a better solution in #2633

**Comment by mariadb-faisalsaeed** [comment]
In 2023, March, still the same problem. I have removed the hyperborder and it appears to be working well :)
