### ISSUE TITLE
Hyper does not start

### ISSUE THREAD

**Issue by MattixNow** [zeit/hyper#3037]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10 Family 1803**: 
- **2.0.0**: 
- **Link of a [Gist](https://gist.github.com/MattixNow/51402f67404f4f79cc4a3d19645195ac) with the contents of your .hyper.js**: 
- **N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hello when i try to launch Hyper app the window is not showing and the process is killing directly. I have the last build of Windows Anniversary Update, before the update Hyper was working prefectly.

see:
https://imgur.com/a/cn9Kkf9

**Comment by jcrben** [comment]
Might be helpful to look at the Windows system logs. Don't know how to do that...

@chabou if you'd like some help triaging I'd be happy to slap labels like Windows on issues every so often

**Comment by MattixNow** [comment]
I try to find problem in Windows system log but nothing..

**Comment by jcrben** [comment]
Could you try building it from source? It's pretty easy if you clone the repo follow the readme instructions. Let me know if you get stuck. ´yarn run dist´ should mostly cover it

**Comment by MattixNow** [comment]
I already try to start Hyper with different path

**Comment by jcrben** [comment]
Did you figure it out? Any lessons learned for someone else who might encounter thid?

**Comment by MattixNow** [comment]
it was just a mistake d'électron. After hard reset of the electron package, Hyper restart

**Comment by MattixNow** [comment]
Sorry if I pushed the closed button too fast

**Comment by jcrben** [comment]
Good to close resolved issues! Still don't understand what went wrong tho.
