### ISSUE TITLE
I have stopped using Hyper because of the cmd-t new tab on mac bug

### ISSUE THREAD

**Issue by marktellez** [zeit/hyper#3150]
it opens dozens of empty tabs and when I close one it closes all. I liked hyper, but it has gotten far too buggy.

**Comment by thedonquixotic** [comment]
@marktellez I'm thinking the same thing, though I'm on Windows and Linux. The most annoying thing to me is that a bunch of the plugins got broken in the last year, and it's basically impossible to figure that stuff out if the plugin developer abandons the project. 

Have you checked out Terminus? It looks interesting. Also the development seems to be more active. I'm going to try it out: https://github.com/Eugeny/terminus

I'm excited by the support for shaders that Hyper has brought but it seems that they simply don't have enough time to get stuff working at a level at which I can trust for production work.

**Comment by sicksid** [comment]
i have this issue aswell, im using version 2.0, when i do cmd + t it works fine, the problem comes after doing cmd+t a few times, it starts opening more tabs every time

**Comment by albinekb** [comment]
This is fixed in canary https://github.com/zeit/hyper/releases/tag/2.1.0-canary.2 by https://github.com/zeit/hyper/pull/3006 . It is however not yet released to stable. I would recommend you to try hyper canary, just change `updateChannel` in your `~/.hyper.js` and restart hyper, it will download the update in the background and then you will get a notification to restart into canary.

**Comment by thedonquixotic** [comment]
Hey I'm still having some weirdness but I updated to Canary and most of it has gone away. Stuff still feels a bit sluggish but that might just be how much stuff I'm putting on my computer to do in the background. 

Thanks for the hard work everyone! Hyper is back on my toolbar and desktop and I intend to keep using it!

**Comment by jcrben** [comment]
Seems like this fix has been released at this point? Can this be closed?

**Comment by chabou** [comment]
Thanks!
