### ISSUE TITLE
Cursor blinks erratically 

### ISSUE THREAD

**Issue by ricardomatias** [zeit/hyper#3318]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X Mojave 10.14.1
- **Hyper.app version**: 2.1.0-canary.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ricardomatias/9e98c4ea5d9b2ac01cd4648476601640
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
The cursos has started blinking erratically since updating to the latest beta release, as shown in this gif:

![blinking-cursor-hyper](https://user-images.githubusercontent.com/8850708/49737210-8a41f700-fc8c-11e8-80e8-a6b717541d2f.gif)

**Comment by iljapanic** [comment]
I'm having the same issue. Also, sometimes encoding gets all messed up and whatever I past gets replaced with a string of identical letters.

**Comment by parktheredcar** [comment]
Happening on windows canary4 as well.

**Comment by chabou** [comment]
@iljapanic 	string of identical letters is another issue https://github.com/zeit/hyper/issues/3314 and it has been fixed with v2.1.0-canary.4

@parktheredcar @ricardomatias can your confirm that your issue occurs without any plugin and only if `cursorBlink ` option is set to `true`?

**Comment by parktheredcar** [comment]
Haven't seen it lately but I'll try and figure out how to reproduce

**Comment by ricardomatias** [comment]
@chabou yes.

Since I haven't seen it again since the last update to version 2.1, I'll assume it was fixed, therefore closing this.

**Comment by chabou** [comment]
@ricardomatias Great news, do not hesitate to comment/reopen if it occurs again.

**Comment by parktheredcar** [comment]
Definitely still happening with all plugins off on windows 10 latest, canary5.

Pretty sure the erratic blinking is a symptom rather than the root issue. In any case, it doesn't blink when `cursorBlink` is `false`.

I am on windows using git bash. This specific setup seems to make it happen reliably, but I haven't been able to dig in to what specifically is doing the damage here:

Tab 1:
ssh into a linux box, running irssi wrapped in a screen session.
Tab 2:
Pane split 4 ways (2 vert 2 horiz). One pane is running webpack-dev-server, another is running nodemon, the others are used for various operations. The nodemon one is usually the first to get weird. Stopping nodemon does not remedy the issue, once a console gets in to this state the only way to fix it is to start over, killing the pane and opening a new one.


The longer it's running the worse the symptoms get. This may be related to #3342

**Comment by parktheredcar** [comment]
Can someone on a different platform confirm these steps? Reliably reproduces on my end.

1. Open hyper

2. Ctrl-shift-d to split pane. At this point, focus is passed to the new pane. Note - doesn't matter if you split pane horizontally or verticaly. Also doesn't matter how you split the pane; using the menu to split the pane will still trigger the issue.

4. Click original pane to return focus. Cursor blinks once, then vanishes. Any further input and the cursor will restore but will not work correctly - maybe two blink loops running at the same time?

**Comment by JeffReeves** [comment]
I can confirm that this is happening in Mac OS as well on Hyper version 2.1.0 (stable). I don't use any plugins.

After splitting panes and shifting focus, one of the panes will have really erratic cursor blinking. The behavior stops after resizing the pane, so I think it's solved by a re-draw of some sort. 

While this is investigated, is there any way to downgrade back to 2.0.0 without an automatic update?

**Comment by MichielLeyman** [comment]
Same issue on MacOS Mojave - perfectly described in #3318
