### ISSUE TITLE
Some Link does not recognize

### ISSUE THREAD

**Issue by mfauzaan** [zeit/hyper#3475]
Links like this does not support on hyper

<img width="566" alt="screen shot 2019-02-13 at 2 38 27 pm" src="https://user-images.githubusercontent.com/25294487/52701926-162e1300-2f9d-11e9-843f-26ea3e9256f4.png">

**Comment by ppot** [comment]
Fixed in canary. Included in next release.

**Comment by mfauzaan** [comment]
@ppot is this update released? 
Im using v3.0.2, and still seems like bug still exists
