### ISSUE TITLE
update will lose preferences before

### ISSUE THREAD

**Issue by mazyi** [zeit/hyper#3589]
when hyper auto update to 3.0.0, the preferences become default

**Comment by juancampa** [comment]
@mazyi what OS are you on?

**Comment by kmpm** [comment]
Same here. Windows 10

**Comment by peterpigler** [comment]
same here, I use windows 10 64 bit as well

**Comment by mgouault** [comment]
Windows 10 64bit too
Since I haven't made a save of the configuration file and since my hyper doesn't work at all with WSL without config I'm pretty much 💀 right now

**Comment by mazyi** [comment]
win10 1809

**Comment by marekkaczkowski** [comment]
Looks like

- `%USERPROFILE%\AppData\Roaming\Hyper\.hyper.js` config is loaded
- instead of `%USERPROFILE%\.hyper.js`

**Comment by MikeCoats** [comment]
I had the same happen to me. In the [docs on the homepage](https://hyper.is/#config-location) there's a small note that explains the config search order.

![image](https://user-images.githubusercontent.com/37802088/57213810-d8f78100-6fdf-11e9-9a04-95101f4db460.png)

It appears that Hyper v3 ships with a config at the `$Env:AppData/Hyper/.hyper.js` location, so is ignoring the old one.

**Comment by skoging** [comment]
> Otherwise it will be moved to the application directory at first run.

This didn't happen for me atleast, the config in application directory was the default one.

**Comment by MikeCoats** [comment]
> This didn't happen for me atleast, the config in application directory was the default one.

I agree. I deleted the one from my application directory then launched Hyper and it recreated a new **default** config. It **did not** copy in my existing config.

Manually copying the old config to the application directory did the trick for me.

**Comment by haiquang9994** [comment]
Can I stop auto upgrade? I want use the old version. Version 3.0.0 have issues.

**Comment by haiquang9994** [comment]
> Can I stop auto upgrade? I want use the old version. Version 3.0.0 have issues.

I run Hyper in windows 10 + WSL
I use tmux, when i detach a session. status bar of tmux still appear on screen.

**Comment by phifa** [comment]
Fixed it. Copy `hyper.js` from `C:\Users\<username>\` to: `C:\Users\<username>\AppData\Roaming\Hyper`

**Comment by pkit** [comment]
> 
> 
> Fixed it. For Windows users copy `hyper.js` from `C:\Users\<username>\` to: `C:\Users\<username>\AppData\Roaming\Hyper` and restart hyper.

It's not a fix but a workaround. The upgrade script should do it.

**Comment by pshah123** [comment]
I copied the prefs over but my plugins are all missing, and my shell looks completely different in color. It's also now ignoring my `PS1` in WSL and the title is now just the path to `bath.exe` instead of the directory as it was before.

Is there any way to downgrade to Hyper 2 and revert changes?

**Comment by juancampa** [comment]
We're discussing Hyper 3 migration in https://github.com/zeit/hyper/issues/3605

> and my shell looks completely different in color.

@pshah123 can you try setting this in your `config` object?

```
    // Whether to use the WebGL renderer. Set it to false to use canvas-based
    // rendering (slower, but supports transparent backgrounds)
    webGLRenderer: false,
```

**Comment by juancampa** [comment]
We're discussing Hyper 3 config migration in https://github.com/zeit/hyper/issues/3605, the plan is to release a migration path as soon as possible

**Comment by pshah123** [comment]
> > and my shell looks completely different in color.
> 
> @pshah123 can you try setting this in your `config` object?
> 
> ```
>     // Whether to use the WebGL renderer. Set it to false to use canvas-based
>     // rendering (slower, but supports transparent backgrounds)
>     webGLRenderer: false,
> ```

The same behaviour occurs unfortunately, it seems this happens most often in WSL -- open issue for it is #3596

**Comment by mgouault** [comment]
Isn't this fixed by https://github.com/zeit/hyper/pull/3610 ?

**Comment by pshah123** [comment]
@mgouault I haven't tested it personally but the color mismatch/conflict still occurs if I migrate my settings manually

**Comment by hammypants** [comment]
Is there anyway to prefer the user folder to the app folder? It is where basically every dot file configuration lives. (Why was it even swapped?)

Additionally...

> Note: config at ~/.hyper.js still supported, but will be ignored, if config in application directory present. Otherwise it will be moved to the application directory at first run.

... reads poorly. `~/.hyperjs` is _not_ still supported, it is merely a migration path.
