### ISSUE TITLE
Screen not cleaning on 3.0

### ISSUE THREAD

**Issue by PolCPP** [zeit/hyper#3596]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10.
- **Hyper.app version**:  3.0.0 (stable)
- **The issue is reproducible in vanilla Hyper.app**: 

After updating to 3.0 Stable, (also happened previously on all the canary versions, just didn't bother to report it) both clear on bash or cls on cmd don't work correctly. I don't think this is a duplicate of  [#3147](https://github.com/zeit/hyper/issues/3147) since i never had problems with it on the 2.0 branch.

![image](https://user-images.githubusercontent.com/1311365/57220629-ad659e00-6fc1-11e9-84b4-20c7971bf85a.png)

It happens randomly, sometimes it clears sometimes it doesn't, sometimes it clears partially like on that screenshot.

**Comment by pshah123** [comment]
This issue previously only occurred on resizing for me in WSL but now occurs whenever the buffer for the screen is changed in any way.

Can be reliably reproduced by just running `ls; clear` in WSL

![Screen recording 2019-05-06 at 03 30 19 PM](https://user-images.githubusercontent.com/6960204/57233198-14ad3d80-7016-11e9-8a8f-c412519903c5.gif)

**Comment by jcolesio** [comment]
I'm currently seeing the same thing.

**Comment by samoldenburg** [comment]
Seems like kind of a major bug to leave in a 3.0.0 release. I seriously doubt this didn't come up in testing...

**Comment by AlexanderLJ** [comment]
Same happening here. Sure is a step up from the bug where a line was getting cut off at the bottom /s

**Comment by X1machinemaker1X** [comment]
Yeah, same thing is happening for me as well. Usually just clicking on the screen a few times clears it up.

**Comment by mhall** [comment]
This is an especially bad problem when using applications like vim or tmux which draw status bars.

**Comment by snassour** [comment]
when I click on the screen after writing `clear`, it clears the terminal, but this is not convenient

**Comment by Glenn-Jaya** [comment]
I'm having the same issue. I'm using git bash as the shell in windows.

**Comment by Glenn-Jaya** [comment]
To quickly get rid of it, for now I do "control =" and "control -" to zoom in and out and it gets rid of it. 
Until it happens again.

**Comment by vonmoraes** [comment]
The same problem here, so far has anyone succeeded?
i managed fix my configurations by following #3605 
also, restore configurations file by default solving the `clear` problem, but when shell environment is changed to `bash` the `clear` problem returns.

**Comment by azefiel** [comment]
Seems like the only viable fix for now is to:

- [block hyper from auto updating](https://github.com/zeit/hyper/issues/1523#issuecomment-489697965)
- downgrade to the [latest 2.x.x release](https://github.com/zeit/hyper/releases/tag/2.1.2) available
- wait until [all 3.0.0 related bugs](https://github.com/zeit/hyper/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+created%3A%3E2019-05-05) get addressed

**Comment by MarxSoul55** [comment]
@azefiel I agree. Judging from all the issues that have been popping up, I think v3 was rushed a bit. Downgrading is definitely a reasonable move.

See: https://github.com/zeit/hyper/issues/3604

**Comment by miklevin** [comment]
Same problem here. Clear only clears part of terminal and varies with number of lines cleared on each re-run. 

The cygwin env solution and webgl true solution don't work for me either. I'm on version 3.0.2.

The Ctrl + followed by Ctrl - solution does work but is tedious.

**Comment by fluoridepsychosis** [comment]
same shit here really annoying

**Comment by miklevin** [comment]
Bad, bad timing with WSL 2 and Windows Terminal dropping later this month.

**Comment by WeslyG** [comment]
- windows 10 1803 - all work currently
- windows 10 1809 - all bad :(
- window 10 1903 - i am update my pc...

**Comment by WeslyG** [comment]
And yep, i am update to 1903 my windows 10 and this bug disappeared.
hyper 3.0.2 + WebGl
![image](https://user-images.githubusercontent.com/12625945/60370458-24427480-9a10-11e9-973b-906e4a38e92d.png)

**Comment by MarxSoul55** [comment]
@WeslyG Good to know! Has anyone else gotten this fixed by upgrading to 1903?

**Comment by MarxSoul55** [comment]
UPDATE:

I'm now on Windows 10 v1903. I installed Hyper 3.0.2 (after uninstalling my previous version of 2.1.2) and ran Debian within WSL (WSL 1, not WSL 2). I ran into the bug again, **however**, I managed to fix it by setting `webGLRenderer` within `.hyper.js` like so:

`webGLRenderer: false`

Did this fix it for anyone else?

**Comment by hakanersu** [comment]
Windows 1903 with Hyper 3.0.2 and webGLRenderer not fixed my problem.

**Comment by MarxSoul55** [comment]
That's unfortunate. I would try to investigate more into this issue myself, but I'm a little short on free time. If anyone else comes to a solution, please let us know.

As a side note — I think it's a little concerning that such a basic issue has been open for 2 months now, and that there are several duplicates explaining the exact same issue. It makes me feel like Hyper isn't really being taken care of. I love Hyper, so I hope that isn't the case.

I hope this bug can be resolved, but I'm not sure it'll be anytime soon. In the meantime, I can suggest [Terminus](https://github.com/Eugeny/terminus), as it doesn't suffer from this issue, and is quite nice overall. I also suggest looking into Microsoft's official terminal as well, although it's still very young.

Cheers!

**Comment by XinRoom** [comment]
Has anyone tried my method? This requires a change upstream, and recompile.  I wonder if it works for others.

https://github.com/zeit/hyper/issues/3641#issuecomment-508381206

**Comment by PolCPP** [comment]
> I can suggest [Terminus](https://github.com/Eugeny/terminus), as it doesn't suffer from this issue, and is quite nice overall. 

[Not really](https://github.com/Eugeny/terminus/issues/28) actually they had the same issue for like 2 years... just a little less annoying

**Comment by fluoridepsychosis** [comment]
Terminus is unbearably slow and bloated even for an electron program

**Comment by MarxSoul55** [comment]
@PolCPP Ah, I didn't know about that, since I don't use git-bash. With regular bash, it works fine, at least for me. Regardless, thanks for the heads up! 👍 

@fluoridepsychosis To each their own, I suppose. I haven't had any issues with bloat/speed, but then again, I'm fortunate to have a beefy machine.

@XinRoom Interesting! I'll have to try this out later on when I'm less busy — I'm not sure when that'll be though. Can someone else verify that his method works?

**Comment by DeanGalvin** [comment]
For reference, this is still an issue. Tried several workarounds found online to no avail.

**Comment by JoshuaSmeda** [comment]
Just an update: problem will persists.

You can manually force a buffer clear by running: `ctrl shift k` but this is not a ideal solution.

Running latest build on Windows: 
![image](https://user-images.githubusercontent.com/39983886/96578266-35825500-12d5-11eb-8c25-3dd6c95010c2.png)
