### ISSUE TITLE
Operator Mono puts cursor on wrong character

### ISSUE THREAD

**Issue by jkup** [zeit/hyper#537]
Hoping this isn't a duplicate!

When I switch my font from the default to Operator Mono the cursor seems to be moved one character to the left. I made a GIF hoping that helps explain the issue!

Am I doing something wrong?

![hyperterm](https://cloud.githubusercontent.com/assets/490294/17283791/608fa1e8-5769-11e6-8ab6-d0c6ecf4de2b.gif)

**Comment by mguldev** [comment]
"Same" issue here. I was writing and saw that when writing "fi", my cursor starts bugging and is moved one character to the right, leaving a blank space between the cursor and what I type.

![issue537](https://cloud.githubusercontent.com/assets/13405305/17286969/d79f4654-579a-11e6-89f9-2db2e0a9518e.jpg)

See above the cursor is moved to the right since I wrote "fi" and it makes all the editing offbeat.

**Comment by MrRio** [comment]
This CSS on the text should fix it:

body { font-feature-settings: "liga" 0; }

**Comment by mguldev** [comment]
I have put `css: 'font-feature-settings: "liga" 0;'` in my .hyperterm.js but that doesn't fix it for me. Editing directly <body>'s style in the inspector and putting the style didn't fix the problem too.

**Comment by BenoitAverty** [comment]
Adding the font-feature-settings property to the element via developer tools worked for me. I ddn't figure out how to put it in the config file to make it work however... But in any case, it'd be much better to make the cursor behave correctly with ligatures and allow the user to keep them.

**Comment by Wojonatior** [comment]
@mguldev I was encountering the same issue when i typed 'fl'. I had initially placed the css within the `css` property, but it looks like the css needs to be placed within the `termCSS` property. I hope that helps you out I with your issue.

**Comment by mguldev** [comment]
@Wojonatior I've put the previous line in the termCSS property, and the problem is still here. Thank you for the advice though.

**Comment by chabou** [comment]
Can you try master and confirm this issue please?

**Comment by yousefissa** [comment]
I am still having the same issue that @mguldev was having. Has anyone figured out a fix? The CSS trick did not work.

**Comment by TooTallNate** [comment]
The `fi` and `fl` issue is happening for me as well. Using Monaco font any Hyper v2 canary.
