### ISSUE TITLE
[Linux] Emacs support - Meta key

### ISSUE THREAD

**Issue by jdormit** [zeit/hyper#552]
I'm running Ubuntu on a laptop with a windows-style keyboard. If I launch an Emacs session in HyperTerm, the `left alt` key doesn't function as a `meta` key. The `escape` key still works, but that's not ideal. I've been looking through the source - I haven't found out what causes this yet. Seems like the fact that the `left alt` key is used in keyboard bindings for the terminal itself is messing up the Emacs keybinding.

The same issue happens in `man` pages - I can scroll down with `ctrl-v` but I can't scroll back up with `alt-v`.

I'm going to keep looking into this myself, but any thoughts or assistance would be appreciated.

**Comment by jdormit** [comment]
This seems to be a duplicate of #499, actually. Any news on that fix?

**Comment by jdormit** [comment]
Also same issue as #274.

**Comment by chadmoore** [comment]
I don't know if it's exactly the same, but definitely related.  I'd say it would be nice to have some way to separate the alt keys so that one is used to enter special characters etc, and the other is used as meta, so things work as expected (readline, emacs, etc..)

**Comment by flybayer** [comment]
I think this was fixed by #686.

**Comment by chadmoore** [comment]
I see the new setting in my config, but alt b (which in iTerm moves my cursor to the left by a word) prints ∫ regardless of the value of the setting.

**Comment by chadmoore** [comment]
Unfortunately I'm still getting:  ∫ instead of jumping a word to the left when I hit alt+b, which works in iTerm.

**Comment by ekmartin** [comment]
@chadmoore is that with version 0.8.1 of Hyper, with `{ modifierKeys: { altIsMeta: true } }` in your configuration? `alt+b` with that set jumps to the previous word for me.

**Comment by chadmoore** [comment]
Ahhh so dumb.  Thanks.  Turns out I had Hyper.app and HyperTerm.app and opened 0.7.something instead.  Whoops.  Thanks again.  Works like a charm now.

**Comment by ekmartin** [comment]
Great! I'll close this then.
