### ISSUE TITLE
Umlauts get eaten in Linux version

### ISSUE THREAD

**Issue by m90** [zeit/hyper#787]
The Linux build (yay for that) seems to have issues displaying non-latin characters (i.e. `Öffentlich`):

![image](https://cloud.githubusercontent.com/assets/1662740/19152564/d7c6a502-8bd2-11e6-80c9-86567e45be91.png)

whereas gnome will display things as expected

![image](https://cloud.githubusercontent.com/assets/1662740/19152638/3be8a0d0-8bd3-11e6-9483-fe64d1cd2829.png)

In addition I am not able to type things like `ü` or something in HyperTerm.

I do not know how this is related to #201 but that seems to be about typing in general.

I am running 0.7.0 (0.7.1 cannot be downloaded atm) on Ubuntu 16.04.

If this is an easy thing to do I'd be more than happy to fix it myself in case someone could give me a few starting hints.

**Comment by albinekb** [comment]
I'll try to check if i can reproduce this with latest master, and see if it's an easy fix (It's probably related to the <meta> tag in the HTML) 

But it could also be more complicated with how we spawn the child processes for the terminal instance, don't know yet :)

If got time you could try pulling down master and building it yourself, to see if this is already fixed in master (doubt it but there's a chance)

👋

**Comment by m90** [comment]
So I just built https://github.com/zeit/hyperterm/commit/36c55a6580ba73b4adc93eead43dcef242d93db5 locally and the problem persists.

**Comment by m90** [comment]
Btw, if you need me to check other things on my now-working locally built Ubuntu setup to further debug things, feel free to ping me.

:wave:

**Comment by programmador** [comment]
Tried 4d8cf7b . The problem still exists - cyrillic chars are displayed as quotation marks in output of `ls` command. But the app can actually display chars - I can see normal cyrillics for example in `apt-get` output.

**Comment by programmador** [comment]
P.S. The OS is debian sid.

**Comment by flybayer** [comment]
This is fixed and can be closed.

**Comment by matheuss** [comment]
Thank you @flybayer 🙌

**Comment by m90** [comment]
This is still happening for me:

![image](https://user-images.githubusercontent.com/1662740/41395541-6295f514-6fae-11e8-8324-7cfcc2490970.png)

Running hyper 2.0.0 on Ubuntu 16.04

**Comment by m90** [comment]
Still happening with Hyper 3 on Ubuntu 18

**Comment by bet4it** [comment]
Try `yay -S hyper-git`
