### ISSUE TITLE
Can't resize tmux panes with the mouse

### ISSUE THREAD

**Issue by drzel** [zeit/hyper#846]
`$ tmux`
ctrl-b %

Unable to resize the pane with the mouse. Instead a character gets inputted for some weird reason.

**Comment by rumpelsepp** [comment]
The neovim mouse support also does not seem to work. Might be a related problem.

**Comment by ekmartin** [comment]
This should be fixed in the latest release (0.8.2).

**Comment by shannonmoeller** [comment]
Still broken for me in 1.0.0.

![image](https://cloud.githubusercontent.com/assets/155164/21111683/aee88560-c070-11e6-8cb8-d034eaa5e132.png)

**Comment by shannonmoeller** [comment]
To be more specific, resizing horizontally works, but resizing vertically does not.

![image](https://cloud.githubusercontent.com/assets/155164/21111862/766cacb0-c071-11e6-9af0-addc1abf593c.png)

**Comment by ppot** [comment]
@shannonmoeller  Please open an issue with vertical specification.
