### ISSUE TITLE
Cannot paste unless window is focused via mouseclick

### ISSUE THREAD

**Issue by CodeTheory** [zeit/hyper#897]
#### Info

Hyper.app version: **0.8.2**
OS: **OSX 10.11.5** _(El Capitan)_
#### Steps to reproduce
1. Blur focus to the Hyper.app window
2. Copy something to your clipboard
3. Tab into Hyper.app
4. Paste

_Additionally:_
Click into Hyper.app after these steps and then try pasting again and it works.

**Comment by jacksonSingleton** [comment]
I'm on Hyper 0.8.1 on El Capitan 10.11.3 and this works perfectly fine for me

**Comment by WillsB3** [comment]
I have this issue on Hyper 0.83 on OS X 10.11.6

**Comment by xjamundx** [comment]
Yeah this used to work fine then started for me about a week or two ago.

**Comment by DanielSiepmann** [comment]
Same issue here with Mac OS Sierra.

**Comment by deanputney** [comment]
I see this issue as well. It will actually start again if I type anything in between clicking on the window and paste. For example: `click on window, paste` works, but `click on window, type 'x', paste` fails.

**Comment by pablomolnar** [comment]
Same as @deanputney on Hyper 0.8.3.873 on OS X 10.12.1 (Sierra)

**Comment by ppot** [comment]
Since PR #892 This should be working since we are not using blur and focus anymore

**Comment by pablomolnar** [comment]
@ppot Still happening in master (6d91ab48d63e30d94c7d43434440772fdb976a7c / 1.4.5).

**Comment by ambethia** [comment]
Oh, thank you for pointing out that it requires a click to focus, that was killing me, it felt so random if it would work or not, at least now I have a work around.

**Comment by matheuss** [comment]
Yo y'all, could you test on latest master? I might have introduced a fix via #1006 👌

**Comment by pablomolnar** [comment]
@matheuss Works great! Thanks!

**Comment by ppot** [comment]
@CodeTheory Test it on resent master if it work. Close 👍

**Comment by CodeTheory** [comment]
Yes, it works for me. Will close.
