### ISSUE TITLE
A lot of output locks up then crashes Hyper

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#94]
Tested under Ubuntu 16.04.

When running:

```
time ls -lR /usr
```

Hyperterm locks up to 1 frame every few seconds and crashes (turns all black then all white) shortly afterwards. 

![image](https://cloud.githubusercontent.com/assets/2193314/16884349/bbf762e4-4a7d-11e6-9a2e-385f3db2036a.png)

By comparison, `gnome-terminal` runs in:

```
real    0m6.967s
user    0m1.372s
sys 0m2.444s
```

This is almost certainly an issue with hterm and a use case they haven't optimized around. As an aside, we've worked a bit to get this usable on xterm.js which runs it in around 10 seconds but there are still improvements to be made.

**Comment by CodeTheory** [comment]
@Tyriar, is this still the case?

**Comment by ppot** [comment]
@CodeTheory  yes 😞

**Comment by nkkollaw** [comment]
I don't know if I'm having the same issue.

With commands that generate a lot of output, Hyper will stop responding.

Memory usage keeps going up, and then it just stops responding.

This command will do that:

time ls -lR /usr

**Comment by kevinelliott** [comment]
This is affecting me too.

**Comment by nadim** [comment]
Had to switch to an alternate terminal today when this popped up.

**Comment by jsullivan** [comment]
I can second this. Deal breaker for me, too. Had to sadly switch back to Terminal.app today, much as I love Hyper.js.

**Comment by emirotin** [comment]
Somehow related I assume: hangs when doing `npm install` of a moderate size (nothing crazy, 20-30 direct dependencies) on macOS (MBP 2017, SSD, 16GB RAM).
Eventually it gets back to normal, but until then it's completely unresponsive.

**Comment by danishmughal** [comment]
Definitely a deal breaker - I want to use hyper but it's impossible to do so when it doesn't really seem to be able to handle giant outputs/logs in a day-to-day dev environment. Hoping some more progress is made on the performance side of things.

**Comment by bntzio** [comment]
This is happening to me too, hyper crashes all the time after I do `npm installs`, what could it be?

**Comment by chabou** [comment]
@bntzio This issue is supposed to be fixed in our canary release (using `xtermjs` instead of `hterm` ).
Can you confirm you use stable release?

**Comment by jsynowiec** [comment]
```
macOS 10.13.1

Hyper 1.4.8

Plugins: 
  hyperterm-atom-dark (1.1.2),
  hyperlinks (0.5.0),
  hypercwd (1.1.1),
  hyperterm-alternatescroll (1.3.0),
  hyper-tabs-enhanced (0.4.2)
```

I have a directory with 266310 text files (csv data dumps) on a remote server. When connected over ssh, executing `ls` freezes Hyper completely. I can't access any tab or do anything other than hitting ⌘+Q loosing all tabs. I can't even open DevTools.

Native Terminal.app works just fine.

Using canary release 2.1.1 it also locks but eventually finishes displaying all output. But there are errors - please see attachments.

This exception is thrown right before displaying all output:
<img width="532" alt="screen shot 2017-11-21 at 19 30 37" src="https://user-images.githubusercontent.com/1029142/33089991-b2344506-cef2-11e7-9e76-98f051234030.png">

There are **20583** following errors listed in console
```
/Users/jakub/.hyper_plugins/node_modules/hypercwd/index.js:32 Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:1050)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:367)
    at _combinedTickCallback (internal/process/next_tick.js:80)
    at process._tickCallback (internal/process/next_tick.js:104)
```

DevTools performance profiling
<img width="1440" alt="screen shot 2017-11-21 at 19 48 00" src="https://user-images.githubusercontent.com/1029142/33090645-ef0c145c-cef4-11e7-920e-fa5425336210.png">

**Comment by bntzio** [comment]
@chabou using Hyper 1.4.8 (stable)

**Comment by AlienHoboken** [comment]
Has any progress been made on this? Still an issue with 1.4.8 stable. I am using zsh instead of bash if it makes any difference?

**Comment by Tyriar** [comment]
@AlienHoboken this issue should be fixed in the Canary build (v2.x).

**Comment by JonnyTizz** [comment]
I've just downloaded 2.0.0-canary.8 and am still having the issue.
Running `time ls -lR /usr` the output initially freezes. After ~30s the output jumps a couple of times, then after a bit more time it starts outputting more fluidly. It is still notably choppier than running the command in Terminal.app.

```
macOS 10.12.6

Hyper 2.0.0-canary.8 (stable)

Plugins: 
  hyper-blink (1.1.2),
  hyper-statusline (1.7.4),
  hyper-tabs-enhanced (0.4.2),
  hyperborder (0.11.1),
  hyper-search (0.0.7)
```
If I can provide any more information, I'd love to.

**Comment by Tyriar** [comment]
It is possible to stall the terminal still (depends largely on your hardware). The cause is that the parser runs on the main thread and is limited to parsing a maximum of 300 characters per frame https://github.com/xtermjs/xterm.js/blob/8c4e6b0e5b8188c361f7e787cca18fadb26d8d33/src/Terminal.ts#L60-L64

The fix for this would be to do this work in a web worker but that's probably a ways off (unless there is a willing contributor).

**Comment by JonnyTizz** [comment]
If it helps, the spec of the Mac I'm working on are as follows:
```
i7-4870HQ CPU @ 2.50GHz
16GB RAM
(is there anything else that would make a difference?)
```
Interestingly, the `time ls -lR /usr` command used ~200% of my CPU at its peak, and a negligible amount of RAM.

Thanks for the speedy reply! I've not ever looked into the xtermjs stuff, or really at web workers, but will have a look. I probably won't be capable or helping out though :(

**Comment by mikeyarce** [comment]
I found this today when I tried using `ack` to search through a folder.  Hyper just froze and I had to force-quit.

**Comment by iamvinny** [comment]
The same is happening for me.. Sometimes I have to run cURL commands on terminal and it returns a big output that instantly crash Hyper.js.

**Comment by timothyis** [comment]
@iamvinny Can you try the canary release? It certainly stress tests your systems but it does't lock up Hyper for me anymore.

**Comment by iamvinny** [comment]
@timothyis , thanks, changing the update channel to canary solved the problem.

**Comment by chabou** [comment]
V2 is out 🎉
